### ISSUE TITLE
GearVR UI Circle only appears in one eye

### ISSUE THREAD

**Issue by daviddewar** [mitchemmc/UE4VRCookbook#1]
From Chapter 2.
1) Download the Chapter 2 project for GearVR
2) open it in Unreal Engine
3) There are some steps to get it working for the phone (set up the initial level in project properties)
4) Package and install on the phone (in my case a Note 5)
5) Launch the app on the phone and launch it
6) put the phone in the Gear VR
7) press the back button after the app launches <== bug.  the circle material only shows on one eye, it should appear in the same location in both eyes

**Comment by mitchemmc** [comment]
Yep, this is a bug in UE4 that was introduced in 4.12/4.13, I do mention it in the book (I had hoped that Epic would fix it before the book was released but I guess not), I would suggest putting it into a UMG widget similar to chapter 6

**Comment by daviddewar** [comment]
Thanks for the quick response.  I'll take a look at the UMG widget approach. I'm currently using UE4 4.13.3
