### ISSUE TITLE
Blueprints in source code are different than what the text read

### ISSUE THREAD

**Issue by nmargie21122** [mitchemmc/UE4VRCookbook#2]
I am using UE 4.15 and reading the kindle edition of the text.

  After completing chapter 4 I notice I have head tracking but the cube is not changing colors. So I downloaded the source code to compare and it seems there is a few things in it that the text never mention. The biggest area seems to be the pawn blueprint, though I did have one or two issues in the text that talked about using a variable that was not mentioned before

Is there an issue with the Kindle edition?

**Comment by nmargie21122** [comment]
I been looking over the sample project it seems much of the extra stuff is for debugging but there does seem to be a few extra things like Sphere tracing in chapter 4 code.

**Comment by mitchemmc** [comment]
Do you remember what the variable was? i'd be curious to have a look and see. Yeah I should have probably taken the debugging stuff out just to avoid confusion, as for the sphere trace it is mention in the exercises part of the chapter at the end I believe

**Comment by nmargie21122** [comment]
Seeing that most of the extra code is debugging stuff I believe the mess up is operator error on my part. This weekend I am going to re read chapter 4 while looking at your code. When I find that variable I will post it on here

**Comment by nmargie21122** [comment]
Hello sorry for getting back to you so late. I think I found the problem, it may be a printing issue

I am reading the Kindle edition so sorry I do not have page numbers
Location 888 (closest thing I have to a page number) Step 3  of "Putting the Functions Together"
  The text says "create a new setter for the Current hit variable." Problem is that variable does not exist 

 Earlier the text has us create a variable called tHit, the source code does not have tHit but has CurrentHit. I am guessing the ‘Curren” got cut off either during printing or in the kindle edition 

Sorry for the confusion

**Comment by nmargie21122** [comment]
Just want to leave a heads up in case others are having some issues. There appears to be two reasons why my chapter 4 code did not work

1. Set Vector Parameter Values for materials
    This is the node that will tell your tube to change colors. I do not remember if it is covered in the text, is make sure you change the "Parameter name" options from "none" to "color"

2. Using wrong Getforwardvector node
    When coding the line trace function we are to get two nodes
   GetforawrdVector
  GetWorldLocation  

    I was not aware that there are two "getforwardvector" nodes. One, the correct one is under utility and is a transform the other, the wrong one I was using is under math. The difference is the transform option targets self while the math option ask for a vector for rotation
